[tool.poetry]
name = "gridworld"
version = "0.1.0"
description = ""
authors = ["alextanhongpin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.4"
black = "^24.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
